eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://13.127.132.74:8761/eureka}

server:
  port: 8090
spring:
  application:
    name: ADMIN-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ls-563b8ec68f8dabb8b2906d3d1e42e400956564f9.c50qwuc20o0g.ap-south-1.rds.amazonaws.com/buildlive_admin
    username: dbmasteruser
    password: 'SudhaRajan'
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

