server:
  port: 7070

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://13.127.132.74:8761/eureka}
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:4200'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE 
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/project/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
#          filters:
#            - AuthenticationFilter

        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/v1/company/**
          filters:
            - AuthenticationFilter

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter
