#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://13.232.2.228:8761/eureka}
#
#server:
#  port: 8070
#spring:
#  application:
#    name: AUTH-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://avnadmin:AVNS_ESgA4tn3IPpnJH_9ilc@mysql-2d3775d9-aravindmunna240-b11d.d.aivencloud.com:11681/buildlive_user?ssl-mode=REQUIRED
#    username: avnadmin
#    password: 'AVNS_ESgA4tn3IPpnJH_9ilc'
##    url: jdbc:mysql://localhost:3306/buildlive_user
##    username: root
##    password: '@77SUDHA'
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#
#
#



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://65.0.180.219:8761/eureka}

server:
  port: 8070
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_YBE-tFQ-tTO-KOjHgos@mysql-1a5bf3cf-infobuildlive360-7bcc.e.aivencloud.com:24001/buildlive_user?ssl-mode=REQUIRED
    username: avnadmin
    password: 'AVNS_YBE-tFQ-tTO-KOjHgos'
  #    url: jdbc:mysql://localhost:3306/buildlive_user
  #    username: root
  #    password: '@77SUDHA'
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect




