eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://13.232.2.228:8761/eureka}

server:
  port: 3000
spring:
  application:
    name: CHAT-SERVICE


