eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://65.0.180.219:8761/eureka}

server:
  port: 8010
spring:
  application:
    name: COMPANY-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_YBE-tFQ-tTO-KOjHgos@mysql-1a5bf3cf-infobuildlive360-7bcc.e.aivencloud.com:24001/buildlive_company?ssl-mode=REQUIRED
    username: avnadmin
    password: 'AVNS_YBE-tFQ-tTO-KOjHgos'
#    url: jdbc:mysql://localhost:3306/buildlive_company
#    username: root
#    password: '@77SUDHA'
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


#deployment

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://3.132.56.186:8761/eureka
#
#server:
#  port: 8010
#spring:
#  application:
#    name: COMPANY-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/buildlive_company
#    username: root
#    password: '@77SUDHA'
#  #    url: jdbc:mysql://localhost:3306/buildlive_company
#  #    username: root
#  #    password: '@77SUDHA'
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect

